# Generated by rust2rpm 24
%bcond_without check

%global crate viu

Name:           rust-viu
Version:        1.4.0
Release:        %autorelease
Summary:        View images right from the terminal

License:        MIT
URL:            https://crates.io/crates/viu
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
View images right from the terminal.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-MIT
%doc README.md
%{_bindir}/viu

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
