# Generated by rust2rpm 23
%bcond_without check

%global crate sniffnet

Name:           rust-sniffnet
Version:        1.0.1
Release:        %autorelease
Summary:        Application to comfortably monitor your network traffic

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/sniffnet
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Application to comfortably monitor your network traffic.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE
%license LICENSE-MIT
%doc CHANGELOG.md
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README.md
%{_bindir}/sniffnet

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
